// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
package docs

var ResourceDescriptions = map[string]string{
	"BeyondLoadBalancer":               "The `kakaocloud_beyond_load_balancer` resource allows you to create and manage a Beyond Load Balancer high availability (HA) group in KakaoCloud.\nThis resource provides configuration options for attaching load balancers, defining access schemes, and associating with a specific VPC.\nIt also exposes detailed status, DNS, and networking information to help monitor and manage HA groups effectively.",
	"Image":                            "The `kakaocloud_image` resource allows you to create and manage custom images in KakaoCloud.\nYou can build images from existing volumes, define descriptions, and use them to launch instances across projects.\nThis resource also provides detailed metadata such as operating system information, disk and memory requirements, sharing status, and visibility settings, enabling flexible and secure image management.",
	"ImageMember":                      "The `kakaocloud_image_member` resource allows you to manage image sharing between projects in KakaoCloud.\nBy using this resource, you can share a specific image with another project, control its sharing status, and track creation and update details.\nThis helps ensure secure and consistent image access across multiple projects within your environment.",
	"Instance":                         "The `kakaocloud_instance` resource allows you to create and manage virtual machine (VM) or bare metal (BM) instances in KakaoCloud.\nYou can specify compute configurations such as instance type, image, and attached volumes, as well as networking details including subnets and security groups.\nThis resource also provides access to detailed metadata and status information, enabling full lifecycle management of instances for various workloads and environments.",
	"Keypair":                          "The `kakaocloud_keypair` resource allows you to create and manage SSH key pairs in KakaoCloud.\nKey pairs are used to securely access instances, and you can either import an existing public key or generate a new key pair.\nThis resource provides lifecycle management for key pairs, including metadata such as fingerprints and ownership details.",
	"KubernetesEngineCluster":          "The `kakaocloud_kubernetes_engine_cluster` resource allows you to create and manage Kubernetes clusters in KakaoCloud.\nYou can configure networking, VPC settings, Kubernetes versions, and public access options, while the resource also provides detailed information on cluster status, upgrade availability, and control plane endpoints.\nThis enables flexible and reliable lifecycle management of containerized workloads in KakaoCloud.",
	"KubernetesEngineClusterNode":      "The `kakaocloud_kubernetes_engine_cluster_node` resource allows you to manage worker nodes in a KakaoCloud Kubernetes Engine cluster.\nYou can cordon, drain, remove, or recreate nodes to maintain cluster stability during upgrades, scaling, or troubleshooting.\nThis resource helps automate node lifecycle operations while ensuring workloads are rescheduled safely.",
	"KubernetesEngineNodePool":         "The `kakaocloud_kubernetes_engine_node_pool` resource allows you to create and manage node pools in a KakaoCloud Kubernetes Engine cluster.\nYou can configure instance types, images, storage, security groups, labels, taints, and autoscaling policies.\nThis resource provides full lifecycle management of node pools, ensuring flexible scaling, workload isolation, and optimized cluster operations.",
	"KubernetesEngineScheduledScaling": "The `kakaocloud_kubernetes_engine_scheduled_scaling` resource allows you to configure scheduled autoscaling rules for node pools in a KakaoCloud Kubernetes Engine cluster.\nYou can define scaling targets, schedules, and execution times to optimize resource usage and cost efficiency.\nThis resource also provides status tracking and execution history for better visibility and operational control.",
	"LoadBalancer":                     "The `kakaocloud_load_balancer` resource allows you to create and manage load balancers in KakaoCloud.\nYou can configure subnet placement, load balancer type, and logging options, while also retrieving detailed information such as VIP addresses, listeners, target groups, and operational status.\nThis resource enables high availability and traffic distribution for applications running in KakaoCloud.",
	"LoadBalancerHealthMonitor":        "The `kakaocloud_load_balancer_health_monitor` resource allows you to configure and manage health checks for load balancer target groups in KakaoCloud.\nYou can define check intervals, response timeouts, retry conditions, and HTTP-specific settings to ensure targets are monitored accurately.\nThis resource provides operational visibility and helps maintain high availability by automatically detecting unhealthy targets.",
	"LoadBalancerL7Policy":             "The `kakaocloud_load_balancer_l7_policy` resource allows you to create and manage Layer 7 (L7) policies for KakaoCloud Load Balancers.\nYou can define advanced traffic management rules such as URL redirects, path-based routing, or forwarding to specific target groups.\nThis resource helps implement flexible application-level routing policies to optimize traffic flow and user experience.",
	"LoadBalancerL7PolicyRule":         "The `kakaocloud_load_balancer_l7_policy_rule` resource allows you to define and manage Layer 7 (L7) policy rules for KakaoCloud Load Balancers.\nYou can configure rules based on paths, headers, hosts, cookies, or file types, with flexible comparison methods and optional inversion.\nThis resource enables advanced traffic routing and fine-grained control over request handling at the application layer.",
	"LoadBalancerListener":             "The `kakaocloud_load_balancer_listener` resource allows you to configure listeners for KakaoCloud Load Balancers.\nListeners define the protocol, port, and SSL/TLS settings for incoming traffic, and can be associated with target groups or Layer 7 (L7) policies.\nThis resource provides fine-grained control over connection handling, security, and routing behavior.",
	"LoadBalancerTargetGroup":          "The `kakaocloud_load_balancer_target_group` resource allows you to create and manage target groups for KakaoCloud Load Balancers.\nYou can configure protocols, algorithms, health monitoring, and session persistence policies, as well as associate target groups with listeners and load balancers.\nThis resource provides detailed metadata and operational states, enabling efficient traffic distribution and backend management.",
	"LoadBalancerTargetGroupMember":    "The `kakaocloud_load_balancer_target_group_member` resource allows you to register and manage target instances in a load balancer target group.\nYou can specify IP addresses, ports, and weights for traffic distribution, as well as optional health check settings.\nThis resource provides detailed metadata and status information, enabling precise control of backend servers within KakaoCloud load balancing.",
	"NetworkInterface":                 "The `kakaocloud_network_interface` resource allows you to create and manage network interfaces in KakaoCloud.\nYou can attach network interfaces to subnets, assign private IPs, and configure security groups or allowed address pairs.\nThis resource provides detailed information such as MAC addresses, device ownership, public IPs, and operational status, enabling flexible and secure network configurations.",
	"PublicIp":                         "The `kakaocloud_public_ip` resource allows you to allocate and manage public IP addresses in KakaoCloud.\nYou can associate public IPs with instances or load balancers, and retrieve detailed information about the linked resource, subnet, and VPC.\nThis resource enables flexible network connectivity and external access management for your cloud workloads.",
	"RouteTable":                       "The `kakaocloud_route_table` resource allows you to create and manage route tables in KakaoCloud.\nYou can define custom routes, associate them with subnets, and configure main route tables within a VPC.\nThis resource also provides detailed information on existing routes, associations, and provisioning status, ensuring flexible and reliable network routing management.",
	"RouteTableAssociation":            "The `kakaocloud_route_table_association` resource allows you to manage the association between route tables and subnets in KakaoCloud.\nYou can specify which subnets are linked to a given route table, ensuring proper routing configuration within a VPC.\nThis resource also provides detailed information about associated subnets, availability zones, and provisioning status.",
	"SecurityGroup":                    "The `kakaocloud_security_group` resource allows you to create and manage security groups in KakaoCloud.\nYou can define inbound and outbound rules to control network traffic at the instance or subnet level, using protocols, ports, and CIDR ranges.\nThis resource also provides metadata and state information, ensuring secure and flexible access management for your cloud environment.",
	"Subnet":                           "The `kakaocloud_subnet` resource allows you to create and manage subnets within a VPC in KakaoCloud.\nYou can define CIDR blocks, availability zones, and associate subnets with route tables.\nThis resource also provides metadata such as project ownership, provisioning status, and sharing options, enabling flexible and organized network segmentation.",
	"SubnetShare":                      "The `kakaocloud_subnet_share` resource allows you to manage subnet sharing between projects in KakaoCloud.\nYou can grant other projects access to a specific subnet by specifying their project IDs, while also retrieving the list of projects that currently have access.\nThis resource helps enable cross-project collaboration and controlled network resource sharing within KakaoCloud.",
	"Volume":                           "The `kakaocloud_volume` resource allows you to create and manage block storage volumes in KakaoCloud.\nYou can define volume size, type, encryption options, and source (image, snapshot, or existing volume).\nThis resource also provides metadata and lifecycle details, such as bootability, mount points, and attachment information, enabling reliable storage management for instances.",
	"VolumeSnapshot":                   "The `kakaocloud_volume_snapshot` resource allows you to create and manage snapshots of block storage volumes in KakaoCloud.\nYou can configure full or incremental snapshots, provide descriptions, and track dependencies between snapshots.\nThis resource also exposes metadata such as size, status, and schedule associations, enabling efficient backup and recovery of volume data.",
	"Vpc":                              "The `kakaocloud_vpc` resource allows you to create and manage Virtual Private Clouds (VPCs) in KakaoCloud.\nA VPC defines an isolated network environment with its own IPv4 CIDR block, subnets, route tables, and internet gateway (IGW).\nYou can specify the CIDR block and name, attach subnets, and manage lifecycle operations such as creation and deletion.\nThis resource also provides metadata about default route tables, DNS support, and provisioning status.",
}

func GetResourceDescription(schema string) string {
	if desc, exists := ResourceDescriptions[schema]; exists {
		return desc
	}
	return ""
}
